# ArgoCD Installation YAML
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: nginx
    repoURL: 'https://github.com/yourusername/your-repo.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}